@echo off
setlocal EnableExtensions

rem Resume the Windows HumanSL GPU workflow without repeating preflight or the
rem first incremental batch. Existing evaluation JSONL files are resumed at
rem game+side+move granularity by run_humansl_windows.ps1.
set PREFLIGHT=0
set INCREMENTAL_FIRST_BATCH=0
set ALLOW_PARTIAL_SGFS=1
set OGS_API_START=79905625
set OGS_API_MAX_REQUESTS=120000
set OGS_API_SLEEP=0.25
set OGS_PLAYER_MAX_PAGES=0
set OGS_PLAYER_GAMES_PAGES=8
set OGS_SEED_GAME_LIMIT=240
set FETCH_REMAINING_BACKGROUND=1
set REFRESH_SGFS=0
set PARALLEL_ENGINES=2
set HUMAN_BATCH_POSITIONS=16
set KATAGO_RESPONSE_TIMEOUT=1800
set PROBE_MAX_QUERIES=64
set PUSH_REMOTE=semanym
set PUSH_REF=main:main

echo [resume] PREFLIGHT=%PREFLIGHT% INCREMENTAL_FIRST_BATCH=%INCREMENTAL_FIRST_BATCH% OGS_API_START=%OGS_API_START%
echo [resume] OGS_PLAYER_MAX_PAGES=%OGS_PLAYER_MAX_PAGES% OGS_PLAYER_GAMES_PAGES=%OGS_PLAYER_GAMES_PAGES% OGS_SEED_GAME_LIMIT=%OGS_SEED_GAME_LIMIT%
echo [resume] FETCH_REMAINING_BACKGROUND=%FETCH_REMAINING_BACKGROUND%
echo [resume] PARALLEL_ENGINES=%PARALLEL_ENGINES% HUMAN_BATCH_POSITIONS=%HUMAN_BATCH_POSITIONS% PROBE_MAX_QUERIES=%PROBE_MAX_QUERIES% PUSH_REMOTE=%PUSH_REMOTE%

call "%~dp0run_humansl_windows.cmd"
exit /b %ERRORLEVEL%
